# Generated by Django 3.2.15 on 2022-08-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220826_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimages',
            options={'verbose_name': 'Изображение для новости', 'verbose_name_plural': 'Изображения для новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Главное изображение'),
        ),
    ]
