# Generated by Django 3.2.15 on 2022-09-27 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220826_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_name', models.CharField(max_length=200, verbose_name='ФИО родителя')),
                ('child_name', models.CharField(max_length=50, verbose_name='ФИО ребенка')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст ребенка')),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('hall', models.CharField(max_length=200, unique=True, verbose_name='Зал для тренировок')),
                ('coach_name', models.CharField(max_length=200, unique=True, verbose_name='ФИО тренера')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d', verbose_name='Главное изображение'),
        ),
    ]
