# Generated by Django 3.2.15 on 2022-09-27 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20220927_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
