# Generated by Django 3.2.15 on 2022-09-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_contact_request_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': ' Контакты'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='coach_name',
            field=models.CharField(max_length=200, verbose_name='ФИО тренера'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='hall',
            field=models.CharField(max_length=200, verbose_name='Зал для тренировок'),
        ),
    ]
