# Generated by Django 3.2.15 on 2022-09-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20220927_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='coach_name',
            field=models.CharField(choices=[('1', 'Маклаков В.П.'), ('2', 'Шустова М.Н.')], max_length=200, verbose_name='ФИО тренера'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='hall',
            field=models.CharField(choices=[('1', 'Спартак'), ('2', 'Школа 33')], max_length=200, verbose_name='Зал для тренировок'),
        ),
    ]
