# Generated by Django 3.2.15 on 2022-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20220930_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_contacted',
            field=models.BooleanField(default=False, verbose_name='Связались'),
        ),
    ]
