# Generated by Django 3.2.15 on 2022-10-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_contact_is_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Главное изображение'),
        ),
    ]
