# Generated by Django 3.2.15 on 2022-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_news_main_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/news/%Y/%m/%d'),
        ),
    ]
