# Generated by Django 3.2.15 on 2022-10-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_newsimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
