# Generated by Django 3.2.15 on 2022-10-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_newsimages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название мероприятия')),
                ('date', models.DateField(verbose_name='Дата мероприятия')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Длительность мероприятия')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('file_name', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
