# Generated by Django 3.2.15 on 2022-10-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20221025_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='father_name',
            field=models.CharField(default=1, max_length=128, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='hall',
            field=models.ManyToManyField(to='mainapp.Hall', verbose_name='Залы'),
        ),
    ]
