# Generated by Django 3.2.15 on 2022-10-27 11:47

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_video_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='hall',
        ),
        migrations.AddField(
            model_name='coach',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.hall', verbose_name='Залы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='coach_name',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hall', chained_model_field='hall', on_delete=django.db.models.deletion.PROTECT, to='mainapp.coach', verbose_name='Тренер'),
        ),
    ]
