# Generated by Django 3.2.15 on 2022-10-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20221027_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='hall',
        ),
        migrations.AddField(
            model_name='coach',
            name='hall',
            field=models.ManyToManyField(to='mainapp.Hall', verbose_name='Залы'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='coach_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.coach', verbose_name='Тренер'),
        ),
    ]
