# Generated by Django 3.2.15 on 2022-11-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20221101_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url_1',
            field=models.TextField(default='https://www.youtube.com/embed/KiTkCnowAdY'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url_2',
            field=models.TextField(default='https://www.youtube.com/embed/KiTkCnowAdY'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url_3',
            field=models.TextField(default='https://www.youtube.com/embed/KiTkCnowAdY'),
        ),
    ]
